#namespace for client
namespace: <NAMESPACE>

# Configuration for the jobs manager
jobsManager:
  # Docker image tag for the jobs manager
  tag: dev
  # Environment variables for the jobs manager
  env:
    # Environment setting (e.g., "dev", "staging", "prod")
    CLIENT_ENV: "dev"
    # Client ID for client authentication
    CLIENT_ID: "<CLIENT_ID>"
    # proxy hostname.
    HTTP_PROXY_HOST: 
    # proxy port.
    HTTP_PROXY_PORT: 
    # username used for proxy authentication if needed.
    HTTP_PROXY_USERNAME: 
    # password used for proxy authentication if needed.
    HTTP_PROXY_PASSWORD:
    # Optional: resource requests for the job
    RESOURCE_REQUESTS: "cpu=2,memory=8Gi" 
    # Optional: resource limits for the job
    RESOURCE_LIMITS: "cpu=2,memory=8Gi"
    # Optional: gpu requests for the job
    GPU_REQUESTS: "nvidia.com/gpu=1"
    # Optional: gpu limits for the job
    GPU_LIMITS: "nvidia.com/gpu=1"
    

# Azure File storage class configuration
storageClass:
  # Set to false if you want to use existing storage class
  create: true
  # Name of the storage class
  name: tb-azurefile
  # Name of the storage provisioner
  provisioner: file.csi.azure.com
  # Whether to allow volume expansion
  allowVolumeExpansion: true
  # Additional parameters for the storage class
  parameters:
    # Azure storage account type
    skuName: Standard_LRS

# Configuration for shared data PVC
sharedData:
  # Name of the PVC for shared data
  name: shared-pvc
  # Size of the PVC for shared data
  storage: 50Gi

# Configuration for logs PVC
logsPvc:
  # Name of the PVC for logs
  name: logs-pvc
  # Size of the PVC for logs
  storage: 10Gi

# Configuration for MySQL PVC
mysqlPvc:
  # Name of the PVC for MySQL data
  name: mysql-pvc
  # Size of the PVC for MySQL data
  storage: 2Gi

# MySQL deployment configuration
mysql:
  # Name of the MySQL deployment
  name: mysql-16

# Cluster Role configuration for RBAC
clusterRole:
  # Set to false if you want to use existing RBAC resources
  create: true
  # Name of the Cluster Role
  name: jobs-manage-rbac

# Secrets configuration
secrets:
  # Whether to create the secret or use existing secret
  create: true
  # Client password
  clientPassword: "<CLIENT_PASSWORD>"


# Docker registry configuration
dockerRegistry:
  # Whether to create the secret or use existing secret
  create: true
  # Name of the Kubernetes Secret for Docker registry credentials
  secretName: regcred
  # Docker registry server URL
  server: https://index.docker.io/v1/
  # Docker registry username
  username: <DOCKER_USERNAME>
  # Docker registry password or access token (consider using Kubernetes Secrets for this)
  password: <DOCKER_REGISTRY_PASSWORD or DOCKER_REGISTRY_TOKEN>
  # Email associated with the Docker registry account
  email: <DOCKER_EMAIL>
