apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: tracebloc-templates
spec:
  volumeName: pvc-ff632903-b704-4780-9f53-a73389741263
  accessModes:
    - ReadWriteMany
  storageClassName: client-storage-class
  resources:
    requests:
      storage: 2Gi
