{{- if .Values.storageClass.create }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageClass.name }}
  namespace: {{ .Release.Namespace }}
provisioner: {{ .Values.storageClass.provisioner }}
allowVolumeExpansion: {{ .Values.storageClass.allowVolumeExpansion }}
reclaimPolicy: {{ .Values.storageClass.reclaimPolicy }}
volumeBindingMode: {{ .Values.storageClass.volumeBindingMode }}
mountOptions:
  - actimeo=30
parameters:
  directoryPerms: "700"
  uid: "999"
  gid: "999"
  reuseAccessPoint: "true"
  fileSystemId: {{ .Values.storageClass.parameters.fileSystemId }}
  provisioningMode: efs-ap
{{- end }}