{{- if .Values.dockerRegistry.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.dockerRegistry.secretName }}
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}