kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ .Values.storageClass.name }}
provisioner: {{ .Values.storageClass.provisioner }}
allowVolumeExpansion: {{ .Values.storageClass.allowVolumeExpansion }}
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000
  - mfsymlinks
  - cache=strict
  - nosharesock
  - actimeo=30
  - noperm
  - file_sharing=on
  - vers=3.0
parameters:
  {{- if eq .Values.storageClass.provisioner "kubernetes.io/no-provisioner" }}
  hostPath: 
    path: {{ .Values.storageClass.parameters.hostPath | default "/mnt/data" }}
  {{- else }}
  skuName: {{ .Values.storageClass.parameters.skuName }}
  {{- end }}
