apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-jobs-manager
spec:
  selector:
    matchLabels:
      app: manager
  replicas: 1
  template:
    metadata:
      labels:
        app: manager
    spec:
      containers:
      - name: api
        image: "tracebloc/jobs-manager:{{ .Values.jobsManager.tag }}"
        imagePullPolicy: Always
        volumeMounts:
          - name: shared-volume
            mountPath: "/data/shared"
        env:
        - name: CLIENT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tracebloc-secrets
              key: CLIENT_PASSWORD
        - name: CLIENT_PVC
          value: "{{ .Values.sharedData.name}}"
        - name: CLIENT_LOGS_PVC
          value: "{{ .Values.logsPvc.name}}"
        - name: MYSQL_HOST
          value: "{{ .Values.mysql.name}}"
        {{- range $key, $value := .Values.jobsManager.env }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
      imagePullSecrets:
      - name: {{ .Values.dockerRegistry.secretName }}
      volumes:
        - name: shared-volume
          persistentVolumeClaim:
            claimName: {{ .Values.sharedData.name}}
      restartPolicy: Always