apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.clientLogsPvc.name }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "0"
spec:
  storageClassName: {{ .Values.storageClass.name }}
  capacity:
    storage: {{ .Values.clientLogsPvc.storage }}
  accessModes:
    - ReadWriteOnce
  hostPath: 
    path: {{ .Values.clientLogsPvc.hostPath }}
---

# PersistentVolumeClaim definition
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.clientLogsPvc.name }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "0"
spec:
  storageClassName: {{ .Values.storageClass.name }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.clientLogsPvc.storage }}
