apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysql.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tracebloc.labels" . | nindent 4 }}
    app: {{ .Values.mysql.name }}
spec:
  ports:
  - port: 3306
  selector:
    app: {{ .Values.mysql.name }}
