apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: tracebloc-resource-monitor
  namespace: {{ .Release.Namespace }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app: tracebloc-resource-monitor
spec:
  selector:
    matchLabels:
      app: tracebloc-resource-monitor
  template:
    metadata:
      labels:
        app: tracebloc-resource-monitor
    spec:
      serviceAccountName: tracebloc-resource-monitor
      # nodeSelector:
      #   trainingset: cpu

      # Start on all nodes (including tainted/dev/GPU nodes)
      tolerations:
        - operator: "Exists"

      containers:
        - name: tracebloc-resource-monitor
          image: "tracebloc/resource-monitor:{{ .Values.jobsManager.tag | default "prod" }}"
          imagePullPolicy: Always

          # Access host /proc and /sys to read node-level metrics
          volumeMounts:
            - name: host-proc
              mountPath: /host/proc
              readOnly: true
            - name: host-sys
              mountPath: /host/sys
              readOnly: true

          env:
            # Standard NVIDIA runtime envs for NVML access without compute
            - name: NVIDIA_VISIBLE_DEVICES
              value: "all"
            - name: NVIDIA_DRIVER_CAPABILITIES
              value: "utility"

            # Script config
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MONITOR_INTERVAL
              value: "30"
            - name: CLIENT_ENV
              value: {{ .Values.jobsManager.env.CLIENT_ENV | default "prod" | quote }}
            - name: CLIENT_ID
              value: {{ .Values.jobsManager.env.CLIENT_ID | quote }}
            - name: CLIENT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tracebloc-secrets
                  key: CLIENT_PASSWORD

          # Keep the container light
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi

      # Graceful stop (optional): send a small final heartbeat if you add logic
      terminationGracePeriodSeconds: 15

      imagePullSecrets:
      - name: {{ .Values.dockerRegistry.secretName }}
      volumes:
        - name: host-proc
          hostPath:
            path: /proc
            type: Directory
        - name: host-sys
          hostPath:
            path: /sys
            type: Directory
