{{- if include "tracebloc.useImagePullSecrets" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tracebloc.registrySecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tracebloc.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}
