{{- $name := include "tracebloc.clientLogsPvc" . -}}
{{- $storage := include "tracebloc.clientLogsStorage" . -}}
{{- if .Values.hostPath.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "tracebloc.clientLogsPvName" . }}
  labels:
    {{- include "tracebloc.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.storageClass.name }}
  capacity:
    storage: {{ $storage }}
  accessModes:
    - ReadWriteOnce
  claimRef:
    name: {{ $name }}
    namespace: {{ .Release.Namespace }}
  hostPath:
    path: /tracebloc/logs
    type: DirectoryOrCreate
---
{{- end }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    {{- include "tracebloc.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.storageClass.name }}
  accessModes:
    - {{ .Values.pvcAccessMode | default "ReadWriteMany" }}
  resources:
    requests:
      storage: {{ $storage }}
