apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Release.Name }}-jobs-manager
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tracebloc.labels" . | nindent 4 }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: manager
