apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: mysql-client
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tracebloc.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: mysql-client
