apiVersion: v1
kind: Service
metadata:
  name: mysql-client
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tracebloc.labels" . | nindent 4 }}
    app: mysql-client
spec:
  ports:
  - port: 3306
  selector:
    app: mysql-client
