apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tracebloc.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tracebloc.labels" . | nindent 4 }}
type: Opaque
data:
  CLIENT_ID: {{ required "clientId is required" .Values.clientId | b64enc | quote }}
  CLIENT_PASSWORD: {{ required "clientPassword is required" .Values.clientPassword | b64enc | quote }}
