{{- $name := include "tracebloc.clientDataPvc" . -}}
{{- $storage := include "tracebloc.clientDataStorage" . -}}
{{- if .Values.hostPath.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ $name }}
  labels:
    {{- include "tracebloc.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.storageClass.name }}
  capacity:
    storage: {{ $storage }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ include "tracebloc.hostPath.data" . }}
    type: DirectoryOrCreate
---
{{- end }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    {{- include "tracebloc.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.storageClass.name }}
  accessModes:
    - {{ .Values.pvcAccessMode | default "ReadWriteMany" }}
  resources:
    requests:
      storage: {{ $storage }}
