---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mysql.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.mysql.name }}
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Values.mysql.name }}
    spec:
      containers:
      - image: tracebloc/mysql-edge
        name: {{ .Values.mysql.name }}
        resources:
          requests:
            memory: "207084Ki"
            cpu: "50m"
        ports:
        - containerPort: 3306
          name: {{ .Values.mysql.name }}
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql/
      imagePullSecrets:
      - name: {{ .Values.dockerRegistry.secretName }}
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: {{ .Values.mysqlPvc.name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysql.name }}
  labels:
    run: {{ .Values.mysql.name }}
spec:
  ports:
  - port: 3306
  selector:
    app: {{ .Values.mysql.name }}