{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tracebloc.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tracebloc.labels" . | nindent 4 }}
type: Opaque
data:
  CLIENT_PASSWORD: {{ required "secrets.clientPassword is required" .Values.secrets.clientPassword | b64enc | quote }}
{{- end }}