{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: tracebloc-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  CLIENT_PASSWORD: {{ .Values.secrets.clientPassword | b64enc | quote }}
{{- end }}