#namespace for client
namespace: <NAMESPACE>

# Configuration for the jobs manager
jobsManager:
  # Docker image tag for the jobs manager
  tag: dev
  # Environment variables for the jobs manager
  env:
    # Environment setting (e.g., "dev", "staging", "prod")
    CLIENT_ENV: "dev"
    # Client Username for client authentication
    CLIENT_ID: "<CLIENT_ID>"
    # proxy hostname.
    HTTP_PROXY_HOST: 
    # proxy port.
    HTTP_PROXY_PORT: 
    # username used for proxy authentication if needed.
    HTTP_PROXY_USERNAME: 
    # password used for proxy authentication if needed.
    HTTP_PROXY_PASSWORD: 
    # Optional: resource requests for the job
    RESOURCE_REQUESTS: "cpu=50m,memory=207084Ki" 
    # Optional: resource limits for the job
    RESOURCE_LIMITS: "cpu=100m,memory=414168Ki"
    # Optional: gpu requests for the job
    GPU_REQUESTS: ""
    # Optional: gpu limits for the job
    GPU_LIMITS: ""

# Configuration for the pods monitor
podsMonitor:
  # Docker image tag for the pods monitor
  tag: dev
  # Environment variables for the pods monitor
  env:
    # Environment setting (e.g., "dev", "staging", "prod")
    CLIENT_ENV: "dev"
    

# AWS EFS storage class configuration
storageClass:
  # Set to false if you want to use existing storage class
  create: true
  # Name of the storage class
  name: tb-awsefs
  # Name of the storage provisioner
  provisioner: efs.csi.aws.com
  # Whether to allow volume expansion
  allowVolumeExpansion: true
  # When to create volume
  volumeBindingMode: Immediate
  # Whether to keep EFS volume when PV is deleted
  reclaimPolicy: Retain
  # Additional parameters for the storage class
  parameters:
    # EFS filesystem ID
    fileSystemId: <FILE_SYSTEM_ID>

# Configuration for shared data PVC
sharedData:
  # Name of the PVC for shared data
  name: shared-pvc
  # Size of the PVC for shared data
  storage: 50Gi

# Configuration for logs PVC
logsPvc:
  # Name of the PVC for logs
  name: logs-pvc
  # Size of the PVC for logs
  storage: 10Gi

# Configuration for MySQL PVC
mysqlPvc:
  # Name of the PVC for MySQL data
  name: mysql-pvc
  # Size of the PVC for MySQL data
  storage: 2Gi

# MySQL deployment configuration
mysql:
  # Name of the MySQL deployment
  name: mysql

# Cluster Role configuration for RBAC
clusterRole:
  # Name of the Cluster Role
  name: jobs-manager-rbac
  # Set to false if you want to use existing RBAC resources
  create: true

# Secrets configuration
secrets:
  # Whether to create the secret or use existing secret
  create: true
  # Client password
  clientPassword: "<CLIENT_PASSWORD>"

# Docker registry configuration
dockerRegistry:
 # Whether to create the secret or use existing secret
  create: true
  # Name of the Kubernetes Secret for Docker registry credentials
  secretName: regcred
  # Docker registry server URL
  server: https://index.docker.io/v1/
  # Docker registry username
  username: <DOCKER_USERNAME>
  # Docker registry password or access token (consider using Kubernetes Secrets for this)
  password: <DOCKER_REGISTRY_PASSWORD or DOCKER_REGISTRY_TOKEN>
  # Email associated with the Docker registry account
  email: <DOCKER_EMAIL>
