#!/usr/bin/env bash
# =============================================================================
#  install-client-helm.sh — Install Tracebloc client Helm chart (step 6)
#  Generates values from defaults + user prompts (namespace, clientId, clientPassword)
#  and GPU detection. Values file is written to HOST_DATA_DIR/values.yaml.
# =============================================================================

TRACEBLOC_HELM_REPO_URL="https://tracebloc.github.io/client"
TRACEBLOC_HELM_REPO_NAME="tracebloc"
TRACEBLOC_CHART_NAME="client"

# Extract a key's value from a simple YAML file (handles "value", 'value', or value)
_extract_yaml_value() {
  local file="$1" key="$2"
  local line
  line=$(grep -E "^${key}:" "$file" 2>/dev/null | head -1)
  [[ -z "$line" ]] && return
  line="${line#*:}"
  line="${line#"${line%%[![:space:]]*}"}"
  line="${line#\"}"; line="${line%\"}"
  line="${line#\'}"; line="${line%\'}"
  printf '%s' "$line"
}

install_client_helm() {
  step "Installing Tracebloc client Helm chart"

  mkdir -p "$HOST_DATA_DIR" "$HOST_DATA_DIR/data" "$HOST_DATA_DIR/logs" "$HOST_DATA_DIR/mysql"
  chmod -R 777 "$HOST_DATA_DIR/data" "$HOST_DATA_DIR/logs" "$HOST_DATA_DIR/mysql" 2>/dev/null || true
  local values_file="${HOST_DATA_DIR}/values.yaml"

  local use_existing=""
  local default_namespace="default"
  local default_client_id=""
  local default_client_password=""

  if [[ -f "$values_file" ]]; then
    info "Existing values file found: $values_file"
    while true; do
      read -r -p "Use values from it as defaults? [Y/n]: " use_existing
      use_existing="$(echo "${use_existing}" | tr '[:upper:]' '[:lower:]')"
      [[ "$use_existing" == "y" || "$use_existing" == "yes" || "$use_existing" == "n" || "$use_existing" == "no" || -z "$use_existing" ]] && break
      warn "Please enter y or n."
    done
    if [[ "$use_existing" == "y" || "$use_existing" == "yes" || -z "$use_existing" ]]; then
      default_client_id=$(_extract_yaml_value "$values_file" "clientId")
      default_client_password=$(_extract_yaml_value "$values_file" "clientPassword")
      [[ -n "$default_client_id" ]] && info "Using existing clientId as default."
      [[ -n "$default_client_password" ]] && info "Using existing clientPassword as default."
    fi
  fi

  # ── Prompt for user inputs ─────────────────────────────────────────────────
  info "Enter values for the Tracebloc client installation:"
  read -r -p "Namespace [${default_namespace}]: " TB_NAMESPACE_INPUT
  TB_NAMESPACE="${TB_NAMESPACE_INPUT:-$default_namespace}"

  echo ""
  step "Client ID & Password"
  echo -e "${BOLD}${YELLOW}Need credentials? Create a client at: ${RESET}${BOLD}\033[1;37mhttps://ai.tracebloc.io/clients${RESET}"
  echo -e "${BOLD}${YELLOW}Setting up a client is free.${RESET}"
  echo ""
  if [[ -n "$default_client_id" ]]; then
    read -r -p "Client ID [${default_client_id}]: " TB_CLIENT_ID_INPUT
    TB_CLIENT_ID="${TB_CLIENT_ID_INPUT:-$default_client_id}"
  else
    read -r -p "Client ID: " TB_CLIENT_ID
  fi
  [[ -z "$TB_CLIENT_ID" ]] && error "Client ID cannot be empty."

  if [[ -n "$default_client_password" ]]; then
    read -r -s -p "Client password [press Enter to keep existing]: " TB_CLIENT_PASSWORD_INPUT
    echo ""
    TB_CLIENT_PASSWORD="${TB_CLIENT_PASSWORD_INPUT:-$default_client_password}"
  else
    read -r -s -p "Client password: " TB_CLIENT_PASSWORD
    echo ""
  fi
  [[ -z "$TB_CLIENT_PASSWORD" ]] && error "Client password cannot be empty."

  # Escape single quotes for YAML: ' -> ''
  TB_CLIENT_PASSWORD_ESCAPED="${TB_CLIENT_PASSWORD//\'/\'\'}"

  # ── GPU limits: nvidia.com/gpu=1 if NVIDIA GPU available, else "" ──────────
  local gpu_val
  if [[ "${GPU_VENDOR:-}" == "nvidia" ]]; then
    gpu_val="nvidia.com/gpu=1"
    info "NVIDIA GPU detected — setting GPU_LIMITS and GPU_REQUESTS to nvidia.com/gpu=1"
  else
    gpu_val=""
    info "No NVIDIA GPU — GPU_LIMITS and GPU_REQUESTS left empty"
  fi

  # ── Write generated values.yaml to .tracebloc ──────────────────────────────
  info "Writing values to $values_file"
  cat <<EOF > "$values_file"
# ============================================================
# Generated by install-k8s.sh — Tracebloc client Helm values
# ============================================================

env:
$([ -n "${CLIENT_ENV:-}" ] && printf '  CLIENT_ENV: "%s"\n' "$CLIENT_ENV")
  RESOURCE_LIMITS: "cpu=2,memory=8Gi"
  RESOURCE_REQUESTS: "cpu=2,memory=8Gi"
  GPU_LIMITS: "$gpu_val"
  GPU_REQUESTS: "$gpu_val"
  RUNTIME_CLASS_NAME: ""

storageClass:
  create: true
  name: client-storage-class
  provisioner: manual
  allowVolumeExpansion: true
  parameters: {}

hostPath:
  enabled: true

pvc:
  mysql: 2Gi
  logs: 10Gi
  data: 50Gi

pvcAccessMode: ReadWriteOnce

clusterScope: true

clientId: "$TB_CLIENT_ID"
clientPassword: '$TB_CLIENT_PASSWORD_ESCAPED'

EOF

  chmod 600 "$values_file" 2>/dev/null || true
  success "Values file written to $values_file"

  # ── Add repo and install ───────────────────────────────────────────────────
  if ! helm repo list 2>/dev/null | grep -q "^${TRACEBLOC_HELM_REPO_NAME}[[:space:]]"; then
    info "Adding Helm repo: $TRACEBLOC_HELM_REPO_URL"
    helm repo add "$TRACEBLOC_HELM_REPO_NAME" "$TRACEBLOC_HELM_REPO_URL"
  fi
  info "Updating Helm repos..."
  helm repo update

  info "Installing $TB_NAMESPACE from $TRACEBLOC_HELM_REPO_NAME/$TRACEBLOC_CHART_NAME in namespace '$TB_NAMESPACE'..."
  helm upgrade --install "$TB_NAMESPACE" "$TRACEBLOC_HELM_REPO_NAME/$TRACEBLOC_CHART_NAME" \
    --namespace "$TB_NAMESPACE" \
    --create-namespace \
    --values "$values_file"

  success "Tracebloc client Helm chart installed in namespace '$TB_NAMESPACE'."
  info "Values file: $values_file"
}
