# Configuration for the jobs manager
jobsManager:
  # Docker image tag for the jobs manager
  tag: latest
  # Environment variables for the jobs manager
  env:
    # Environment setting (e.g., "dev", "staging", "prod")
    CLIENT_ENV: "dev"
    # Client Username for client authentication
    CLIENT_USERNAME: "testedge"
    # proxy hostname.
    HTTP_PROXY_HOST: 
    # proxy port.
    HTTP_PROXY_PORT: 
    # username used for proxy authentication if needed.
    HTTP_PROXY_USERNAME: 
    # password used for proxy authentication if needed.
    HTTP_PROXY_PASSWORD: 
    # Optional: resource requests for the job
    RESOURCE_REQUESTS: "cpu=50m,memory=207084Ki" 
    # Optional: resource limits for the job
    RESOURCE_LIMITS: "cpu=100m,memory=414168Ki"
    # Optional: gpu requests for the job
    GPU_REQUESTS: "nvidia.com/gpu=1"
    # Optional: gpu limits for the job
    GPU_LIMITS: "nvidia.com/gpu=1"

# File storage class configuration
storageClass:
  # Set to false if you want to use existing storage class
  create: true
  # Name of the storage class
  name: tb-azurefile
  # Name of the storage provisioner
  provisioner: manual
  # Whether to allow volume expansion
  allowVolumeExpansion: true
  # Additional parameters for the storage class
  parameters:
    # storage account type (Standard_LRS is recommended for development)
    skuName: Standard_LRS
    # Ensure SMB protocol is used
    protocol: smb
    # Enable file sharing features
    enableSmb: "true"
    # Enable support for macOS
    osType: "darwin"


# Configuration for shared data PVC
sharedData:
  # Name of the PVC for shared data
  name: shared-pvc-16
  # Size of the PVC for shared data
  storage: 50Gi
  # host path for shared data
  hostPath: /Documents/data/shared-data


# Configuration for logs PVC
logsPvc:
  # Name of the PVC for logs
  name: logs-pvc-16
  # Size of the PVC for logs
  storage: 10Gi
  # host path for logs
  hostPath: /Documents/data/logs

# Configuration for MySQL PVC
mysqlPvc:
  # Name of the PVC for MySQL data
  name: mysql-pvc-16
  # Size of the PVC for MySQL data
  storage: 2Gi
  # host path for MySQL data
  hostPath: /Documents/data/mysql

# MySQL deployment configuration
mysql:
  # Name of the MySQL deployment
  name: mysql-16

# Cluster Role configuration for RBAC
clusterRole:
  # Set to false if you want to use existing RBAC resources
  create: true
  # Name of the Cluster Role
  name: jobs-manage-rbac

# Secrets configuration
secrets:
  # Whether to create the secret or use existing secret
  create: true
  # Client password
  clientPassword: ""


# Docker registry configuration
dockerRegistry:
  # Whether to create the secret or use existing secret
  create: true
  # Name of the Kubernetes Secret for Docker registry credentials
  secretName: regcred
  # Docker registry server URL
  server: https://index.docker.io/v1/
  # Docker registry username
  username: xyz
  # Docker registry password or access token (consider using Kubernetes Secrets for this)
  password: pass
  # Email associated with the Docker registry account
  email: xyz@tracebloc.io