#namespace for client
namespace: <NAMESPACE>

# Configuration for the jobs manager
jobsManager:
  # Docker image tag for the jobs manager
  tag: dev
  # Environment variables for the jobs manager
  env:
    # Client ID
    CLIENT_ID: "<CLIENT_ID>"
    # Client ENV
    CLIENT_ENV: "dev"
    # Optional: proxy hostname.
    HTTP_PROXY_HOST: 
    # Optional: proxy port.
    HTTP_PROXY_PORT: 
    # Optional: username used for proxy authentication if needed.
    HTTP_PROXY_USERNAME: 
    # Optional: password used for proxy authentication if needed.
    HTTP_PROXY_PASSWORD: 
    # Optional: resource requests for the job
    RESOURCE_REQUESTS: "cpu=2,memory=8Gi" 
    # Optional: resource limits for the job
    RESOURCE_LIMITS: "cpu=2,memory=8Gi"
    # Optional: gpu requests for the job
    GPU_REQUESTS:
    # Optional: gpu requests for the job e.g. "nvidia.com/gpu=1"
    GPU_LIMITS:
    # Optional: gpu limits for the job e.g. "nvidia.com/gpu=1"

    # Optional: runtime class name for runing job with gpu (required for k3s)
    RUNTIME_CLASS_NAME: "nvidia"

# Configuration for the pods monitor
podsMonitor:
  # Docker image tag for the pods monitor
  tag: dev
  # Environment variables for the pods monitor
  env:
    # Environment setting (e.g., "dev", "staging", "prod")
    CLIENT_ENV: "dev"
    # Client Username for client authentication
    CLIENT_ID: "<CLIENT_ID>"
    # proxy hostname.
    HTTP_PROXY_HOST:
    # proxy port.
    HTTP_PROXY_PORT:
    # username used for proxy authentication if needed.
    HTTP_PROXY_USERNAME:
    # password used for proxy authentication if needed.
    HTTP_PROXY_PASSWORD:

# File storage class configuration
storageClass:
  # Set to true to create a new storage class, false to use existing. Be careful not to overwrite existing datafiles by setting it true.
  create: true
  # Name of the storage class
  name: client-storage-class
  # Name of the storage provisioner
  provisioner: manual
  # Whether to allow volume expansion
  allowVolumeExpansion: true
  # Additional parameters for the storage class
  parameters:
    # storage account type (Standard_LRS is recommended for development)
    skuName: Standard_LRS
    # Ensure SMB protocol is used
    protocol: smb
    # Enable file sharing features
    enableSmb: "true"
    # Enable support for your OS
    osType: <OS_TYPE> # Use "darwin" for macOS, "linux" for Linux systems, "windows" for Windows

# Configuration for  data PVC
sharedData:
  # Name of the PVC for client data
  name: client-pvc
  # Size of the PVC for client data
  storage: 50Gi
  # host path for client data
  hostPath: "<Input path to data folder>/shared_data"

# Configuration for logs PVC
logsPvc:
  # Name of the PVC for logs
  name: logs-pvc
  # Size of the PVC for logs
  storage: 10Gi
   # host path for client logs
  hostPath: "<Input path to data folder>/logs"

# Configuration for MySQL PVC
mysqlPvc:
  # Name of the PVC for MySQL data
  name: mysql-pvc
  # Size of the PVC for MySQL data
  storage: 2Gi
   # host path for MySQL data
  hostPath: "<Input path to data folder>/mysql"

# MySQL deployment configuration
mysql:
  # Name of the MySQL deployment has to match the ingestor MYSQL_HOST in ingestor-job.yaml.
  name: mysql

# Cluster Role configuration for RBAC
clusterRole:
  # Set to false if you want to use existing RBAC resources
  create: true
  # Name of the Cluster Role
  name: jobs-manage-rbac

# Secrets configuration
secrets:
  # Whether to create the secret or use existing secret
  create: true
  # Client password
  clientPassword: "<CLIENT_PASSWORD>"


# Docker registry configuration
dockerRegistry:
  # Whether to create the secret or use existing secret
  create: true
  # Name of the Kubernetes Secret for Docker registry credentials
  secretName: regcred
  # Docker registry server URL
  server: https://index.docker.io/v1/
  # Docker registry username
  username: <DOCKER_USERNAME>
  # Docker registry password or access token (consider using Kubernetes Secrets for this)
  password: <DOCKER_REGISTRY_PASSWORD or DOCKER_REGISTRY_TOKEN>
  # Email associated with the Docker registry account
  email: <DOCKER_EMAIL>
