#namespace for client
namespace: <NAMESPACE_ID>

# Configuration for the jobs manager
jobsManager:
  # Docker image tag for the jobs manager
  tag: dev
  # Environment variables for the jobs manager
  env:
    # Client ID
    CLIENT_ID: "<CLIENT_ID>"
    # Client ENV
    CLIENT_ENV: "dev"
    # Optional: proxy hostname.
    HTTP_PROXY_HOST: 
    # Optional: proxy port.
    HTTP_PROXY_PORT: 
    # Optional: username used for proxy authentication if needed.
    HTTP_PROXY_USERNAME: 
    # Optional: password used for proxy authentication if needed.
    HTTP_PROXY_PASSWORD: 
    # Optional: resource requests for the job
    RESOURCE_REQUESTS: "cpu=50m,memory=207084Ki" 
    # Optional: resource limits for the job
    RESOURCE_LIMITS: "cpu=100m,memory=414168Ki"
    # Optional: gpu requests for the job
    GPU_REQUESTS:
    # Optional: gpu limits for the job
    GPU_LIMITS:

# File storage class configuration
storageClass:
  # Set to false if you want to use existing storage class
  create: true
  # Name of the storage class
  name: client-storage-class
  # Name of the storage provisioner
  provisioner: manual
  # Whether to allow volume expansion
  allowVolumeExpansion: true
  # Additional parameters for the storage class
  parameters:
    # storage account type (Standard_LRS is recommended for development)
    skuName: Standard_LRS
    # Ensure SMB protocol is used
    protocol: smb
    # Enable file sharing features
    enableSmb: "true"
    # Enable support for macOS
    osType: "darwin"

# Configuration for  data PVC
sharedData:
  # Name of the PVC for client data
  name: client-pvc
  # Size of the PVC for client data
  storage: 50Gi
  # host path for client data
  hostPath: "<Input path to data folder>/shared_data"

# Configuration for logs PVC
logsPvc:
  # Name of the PVC for logs
  name: logs-pvc
  # Size of the PVC for logs
  storage: 10Gi
   # host path for client logs
  hostPath: "<Input path to data folder>/logs"

# Configuration for MySQL PVC
mysqlPvc:
  # Name of the PVC for MySQL data
  name: mysql-pvc
  # Size of the PVC for MySQL data
  storage: 2Gi
   # host path for MySQL data
  hostPath: "<Input path to data folder>/mysql"

# MySQL deployment configuration
mysql:
  # Name of the MySQL deployment
  name: mysql-client

# Cluster Role configuration for RBAC
clusterRole:
  # Set to false if you want to use existing RBAC resources
  create: true
  # Name of the Cluster Role
  name: jobs-manage-rbac

# Secrets configuration
secrets:
  # Whether to create the secret or use existing secret
  create: true
  # Client password
  clientPassword: "<CLIENT_PASSWORD>"


# Docker registry configuration
dockerRegistry:
  # Whether to create the secret or use existing secret
  create: true
  # Name of the Kubernetes Secret for Docker registry credentials
  secretName: regcred
  # Docker registry server URL
  server: https://index.docker.io/v1/
  # Docker registry username
  username: <DOCKER_USERNAME>
  # Docker registry password or access token (consider using Kubernetes Secrets for this)
  password: <DOCKER_REGISTRY_PASSWORD or DOCKER_REGISTRY_TOKEN>
  # Email associated with the Docker registry account
  email: <DOCKER_EMAIL>
