# GENERATED by scripts/gen-envelope-embed.sh — do not hand-edit.
# Golden vectors from client-runtime/envelope_contract.json
# (contract v1, pin: scripts/.client-runtime-ref).
#
# <label>|<allocatable cpu>|<allocatable memory>|<expected output>
TB_ENVELOPE_VECTORS=(
  "field-8c-32gi|8|32Gi|cpu=7,memory=29Gi"
  "field-16c-64gi|16|64Gi|cpu=15,memory=61Gi"
  "field-4c-16gi|4|16Gi|cpu=3,memory=13Gi"
  "k8s-millicores-and-mi|15500m|63928Mi|cpu=14,memory=59Gi"
  "k8s-raw-bytes|8|33285996544|cpu=7,memory=28Gi"
  "laptop-2c-8gi|2|8Gi|cpu=1,memory=5Gi"
  "exact-floor|2|5Gi|cpu=1,memory=2Gi"
  "one-byte-under-mem-floor|2|5368709119|"
  "one-milli-under-cpu-floor|1999m|8Gi|"
  "wsl2-too-small-4gi|4|4Gi|"
  "absurdly-small|500m|512Mi|"
  "unparseable-cpu|eight|8Gi|"
  "unparseable-memory|8|lots|"
)

# Multi-node cases pin the ANCHOR_LARGEST selection rule — the part that
# was never written down. Rows are:
#   <label>|<node lines, newline-escaped as \n>|<expected output>
TB_ENVELOPE_ANCHOR_VECTORS=(
  "heterogeneous-incomparable|8 16Gi\n4 32Gi|cpu=7,memory=13Gi"
  "server-plus-small-agent|16 64Gi\n2 8Gi|cpu=15,memory=61Gi"
  "identical-pair|8 32Gi\n8 32Gi|cpu=7,memory=29Gi"
  "one-cordoned-out|4 16Gi|cpu=3,memory=13Gi"
)
