# GENERATED by scripts/gen-envelope-embed.sh — do not hand-edit.
# Golden vectors from client-runtime/envelope_contract.json
# (contract v2, pin: scripts/.client-runtime-ref).
#
# <label>|<allocatable cpu>|<allocatable memory>|<expected output>
TB_ENVELOPE_VECTORS=(
  "field-8c-32gi|8|32Gi|cpu=7,memory=29Gi"
  "field-16c-64gi|16|64Gi|cpu=15,memory=61Gi"
  "field-4c-16gi|4|16Gi|cpu=3,memory=13Gi"
  "k8s-millicores-and-mi|15500m|63928Mi|cpu=14,memory=59Gi"
  "k8s-raw-bytes|8|33285996544|cpu=7,memory=28Gi"
  "laptop-2c-8gi|2|8Gi|cpu=1,memory=5Gi"
  "exact-floor|2|5Gi|cpu=1,memory=2Gi"
  "one-byte-under-mem-floor|2|5368709119|"
  "one-milli-under-cpu-floor|1999m|8Gi|"
  "wsl2-too-small-4gi|4|4Gi|"
  "absurdly-small|500m|512Mi|"
  "unparseable-cpu|eight|8Gi|"
  "unparseable-memory|8|lots|"
)

# Multi-node cases pin the ANCHOR_LARGEST selection rule — the part that
# was never written down. Rows are:
#   <label>|<node lines, newline-escaped as \n>|<expected output>
TB_ENVELOPE_ANCHOR_VECTORS=(
  "heterogeneous-incomparable|8 16Gi\n4 32Gi|cpu=7,memory=13Gi"
  "server-plus-small-agent|16 64Gi\n2 8Gi|cpu=15,memory=61Gi"
  "identical-pair|8 32Gi\n8 32Gi|cpu=7,memory=29Gi"
  "one-cordoned-out|4 16Gi|cpu=3,memory=13Gi"
)

# Topology vectors (backend#2221): the VM real size in, an honest node
# count and per-node memory cap out. Rows are:
#   <label>|<vm cpu>|<vm memory>|<requested nodes>|<expected output>
#
# where the expected output is what _honest_topology must PRINT --
#   nodes=N,cap=BYTES,cpu_honest=0|1,viable=0|1
# for a readable VM, and the empty string when the VM is unreadable (the
# function emits nothing, which the caller must NOT read as one node).
TB_TOPOLOGY_VECTORS=(
  "stock-macos-vm-7.75gi|10|8321712128|2|nodes=1,cap=7247970304,cpu_honest=1,viable=1"
  "vm-16gi-want-2|8|17179869184|2|nodes=2,cap=8053063680,cpu_honest=0,viable=1"
  "vm-16gi-want-4|8|17179869184|4|nodes=3,cap=5368709120,cpu_honest=0,viable=1"
  "vm-32gi-want-2|16|34359738368|2|nodes=2,cap=16642998272,cpu_honest=0,viable=1"
  "exact-two-nodes|8|11811160064|2|nodes=2,cap=5368709120,cpu_honest=0,viable=1"
  "one-byte-under-two-nodes|8|11811160063|2|nodes=1,cap=10737418239,cpu_honest=1,viable=1"
  "single-node-requested|8|34359738368|1|nodes=1,cap=33285996544,cpu_honest=1,viable=1"
  "vm-too-small-4gi|4|4294967296|2|nodes=1,cap=3221225472,cpu_honest=1,viable=0"
  "vm-cpu-starved|1|17179869184|1|nodes=1,cap=16106127360,cpu_honest=1,viable=0"
  "vm-unparseable-memory|8|lots|2|"
  "vm-unparseable-cpu|eight|8Gi|2|"
)
