# GENERATED by scripts/gen-installer-parity.sh — do not hand-edit.
# Source of truth: scripts/tests/fixtures/installer_parity.json (client#772)
#
# One row per cluster state. Fields, pipe-separated:
#   label|nodes|carried|carried_provenance|override|size|provenance|undersized|unschedulable|limits
#
# `nodes` is semicolon-separated node lines, as kubectl's jsonpath emits them:
# '<cpu> <memory>' plus an optional third field, '<spec.unschedulable>'.
# Unschedulable is omitempty, so a schedulable node emits nothing there and
# both readers see a two-field line -- which is why the pre-backend#2237 rows
# below still carry two fields. Only a CORDONED node emits the literal 'true'.
# `carried` is 'none', 'read-fails', 'read-empty',
# or the RESOURCE_LIMITS value a previous release carries.
# `limits` is what RESOURCE_LIMITS gets: `size` minus its cpu dimension
# (backend#2418 L0.2). NOT the same string as `size` any more.
#
# Machine-sized rows (size_from=contract in the JSON) carry verdicts DERIVED
# from envelope_contract.json (contract_version 4: overhead
# 650m / 1792 MiB, floor 1000m / 2048 MiB),
# after reproducing 13 single-node and
# 4 multi-node golden vectors. Carried and overridden rows are hand-pinned.
# schema_version 3

TB_PARITY_ROWS=(
  "viable-single-node|8 32Gi|none|||cpu=7,memory=30Gi|installer|0|0|memory=30Gi"
  "viable-large-node|16 64Gi|none|||cpu=15,memory=62Gi|installer|0|0|memory=62Gi"
  "heterogeneous-incomparable|8 16Gi;4 32Gi|none|||cpu=7,memory=14Gi|installer|0|0|memory=14Gi"
  "node-order-reversed|4 32Gi;8 16Gi|none|||cpu=7,memory=14Gi|installer|0|0|memory=14Gi"
  "one-unparseable-one-valid|16 64GB;8 32Gi|none|||cpu=7,memory=30Gi|installer|0|0|memory=30Gi"
  "unparseable-cpu-one-valid|sixteen 64Gi;8 32Gi|none|||cpu=7,memory=30Gi|installer|0|0|memory=30Gi"
  "all-nodes-unparseable|sixteen 64GB;eight lots|none|||cpu=1,memory=2Gi|installer|0|0|memory=2Gi"
  "below-floor-but-requestable|2 3Gi|none|||cpu=1,memory=1Gi|installer|1|0|memory=1Gi"
  "too-small-to-request|500m 512Mi|none|||cpu=1,memory=2Gi|installer|0|1|memory=2Gi"
  "exact-floor|1650m 4026531840|none|||cpu=1,memory=2Gi|installer|0|0|memory=2Gi"
  "carried-read-fails|8 32Gi|read-fails|||cpu=7,memory=30Gi|installer|0|0|memory=30Gi"
  "carried-read-empty|8 32Gi|read-empty|||cpu=7,memory=30Gi|installer|0|0|memory=30Gi"
  "carried-size-no-marker|8 32Gi|cpu=4,memory=12Gi|||cpu=4,memory=12Gi|unknown|0|0|memory=12Gi"
  "carried-size-user-marker|8 32Gi|cpu=4,memory=12Gi|user||cpu=4,memory=12Gi|user|0|0|memory=12Gi"
  "carried-size-installer-marker|8 32Gi|cpu=4,memory=12Gi|installer||cpu=4,memory=12Gi|installer|0|0|memory=12Gi"
  "carried-size-junk-marker|8 32Gi|cpu=4,memory=12Gi|banana||cpu=4,memory=12Gi|unknown|0|0|memory=12Gi"
  "carried-historic-literal|8 32Gi|cpu=2,memory=8Gi|user||cpu=7,memory=30Gi|installer|0|0|memory=30Gi"
  "install-time-override|8 32Gi|none||cpu=4,memory=16Gi|cpu=4,memory=16Gi|user|0|0|memory=16Gi"
  "cordoned-large-node-skipped|16 64Gi true;4 16Gi|none|||cpu=3,memory=14Gi|installer|0|0|memory=14Gi"
  "cordoned-small-node-ignored|16 64Gi;4 16Gi true|none|||cpu=15,memory=62Gi|installer|0|0|memory=62Gi"
  "all-nodes-cordoned|16 64Gi true;8 32Gi true|none|||cpu=1,memory=2Gi|installer|0|0|memory=2Gi"
  "explicit-unschedulable-false-is-schedulable|8 32Gi false|none|||cpu=7,memory=30Gi|installer|0|0|memory=30Gi"
)

# kubelet drop-in reservation shape (backend#2460); see the JSON's kubelet_reservation.purpose
TB_PARITY_RESERVATION_PLATFORMS_VAR="TB_KUBELET_RESERVATION_PLATFORMS"
TB_PARITY_RESERVATION_UNMEASURED_PROBE="nowhere"
TB_PARITY_RESERVATION_EMITTED_MEASURED=(
  "enforceNodeAllocatable:"
  "kubeReserved:"
  "systemReserved:"
  "evictionHard:"
  "memory.available:"
)
TB_PARITY_RESERVATION_NEVER_UNMEASURED=(
  "enforceNodeAllocatable"
  "kubeReserved"
  "systemReserved"
  "evictionHard"
  "memory.available"
)
TB_PARITY_RESERVATION_NEVER_RESTATED=(
  "imagefs.available"
  "nodefs.available"
)
TB_PARITY_RESERVATION_ALWAYS=(
  "apiVersion: kubelet.config.k8s.io/v1beta1"
  "kind: KubeletConfiguration"
  "imageGCHighThresholdPercent:"
  "imageGCLowThresholdPercent:"
  "imageMinimumGCAge:"
)
