# GENERATED by scripts/gen-installer-parity.sh — do not hand-edit.
# Source of truth: scripts/tests/fixtures/installer_parity.json (client#772)
#
# One row per cluster state. Fields, pipe-separated:
#   label|nodes|carried|carried_provenance|override|size|provenance|undersized|unschedulable
#
# `nodes` is semicolon-separated '<cpu> <memory>' pairs, exactly the lines
# kubectl's jsonpath emits. `carried` is 'none', 'read-fails', 'read-empty',
# or the RESOURCE_LIMITS value a previous release carries.
# schema_version 1

TB_PARITY_ROWS=(
  "viable-single-node|8 32Gi|none|||cpu=7,memory=29Gi|installer|0|0"
  "viable-large-node|16 64Gi|none|||cpu=15,memory=61Gi|installer|0|0"
  "heterogeneous-incomparable|8 16Gi;4 32Gi|none|||cpu=7,memory=13Gi|installer|0|0"
  "node-order-reversed|4 32Gi;8 16Gi|none|||cpu=7,memory=13Gi|installer|0|0"
  "one-unparseable-one-valid|16 64GB;8 32Gi|none|||cpu=7,memory=29Gi|installer|0|0"
  "unparseable-cpu-one-valid|sixteen 64Gi;8 32Gi|none|||cpu=7,memory=29Gi|installer|0|0"
  "all-nodes-unparseable|sixteen 64GB;eight lots|none|||cpu=2,memory=8Gi|installer|0|0"
  "below-floor-but-requestable|2 4Gi|none|||cpu=1,memory=1Gi|installer|1|0"
  "too-small-to-request|500m 512Mi|none|||cpu=2,memory=8Gi|installer|0|1"
  "exact-floor|2 5Gi|none|||cpu=1,memory=2Gi|installer|0|0"
  "carried-read-fails|8 32Gi|read-fails|||cpu=7,memory=29Gi|installer|0|0"
  "carried-read-empty|8 32Gi|read-empty|||cpu=7,memory=29Gi|installer|0|0"
  "carried-size-no-marker|8 32Gi|cpu=4,memory=12Gi|||cpu=4,memory=12Gi|unknown|0|0"
  "carried-size-user-marker|8 32Gi|cpu=4,memory=12Gi|user||cpu=4,memory=12Gi|user|0|0"
  "carried-size-installer-marker|8 32Gi|cpu=4,memory=12Gi|installer||cpu=4,memory=12Gi|installer|0|0"
  "carried-size-junk-marker|8 32Gi|cpu=4,memory=12Gi|banana||cpu=4,memory=12Gi|unknown|0|0"
  "carried-historic-literal|8 32Gi|cpu=2,memory=8Gi|user||cpu=7,memory=29Gi|installer|0|0"
  "install-time-override|8 32Gi|none||cpu=4,memory=16Gi|cpu=4,memory=16Gi|user|0|0"
)
