#!/usr/bin/env bash
#
# gen-installer-parity.sh — flatten scripts/tests/fixtures/installer_parity.json
# into a sourceable bash table (client#772).
#
# bats has no guaranteed JSON parser (jq is not a prerequisite — see the
# helm-namespace note in lib/install-client-helm.sh), so the shared fixture is
# flattened for the bash side exactly the way envelope_vectors.bash already is.
# The Pester side reads the JSON directly; PowerShell has ConvertFrom-Json.
#
# One fixture, two readers. If they ever disagree, one has drifted — which is
# the whole point of the file.
#
# Usage:
#   scripts/gen-installer-parity.sh           # regenerate the bash table
#   scripts/gen-installer-parity.sh --check   # verify, change nothing (CI)

set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."

SRC="scripts/tests/fixtures/installer_parity.json"
OUT="scripts/tests/fixtures/installer_parity.bash"

CHECK=0
[[ "${1:-}" == "--check" ]] && CHECK=1

[[ -f "$SRC" ]] || { echo "[ERROR] $SRC is missing" >&2; exit 1; }
command -v python3 >/dev/null 2>&1 || {
  echo "[ERROR] python3 is required to regenerate the parity table" >&2
  exit 1
}

_emit() {
  python3 - "$SRC" <<'PY'
import json, sys

with open(sys.argv[1]) as fh:
    spec = json.load(fh)

print("# GENERATED by scripts/gen-installer-parity.sh — do not hand-edit.")
print("# Source of truth: scripts/tests/fixtures/installer_parity.json (client#772)")
print("#")
print("# One row per cluster state. Fields, pipe-separated:")
print("#   label|nodes|carried|carried_provenance|override|size|provenance|undersized|unschedulable")
print("#")
print("# `nodes` is semicolon-separated node lines, as kubectl's jsonpath emits them:")
print("# '<cpu> <memory>' plus an optional third field, '<spec.unschedulable>'.")
print("# Unschedulable is omitempty, so a schedulable node emits nothing there and")
print("# both readers see a two-field line -- which is why the pre-backend#2237 rows")
print("# below still carry two fields. Only a CORDONED node emits the literal 'true'.")
print("# `carried` is 'none', 'read-fails', 'read-empty',")
print("# or the RESOURCE_LIMITS value a previous release carries.")
print(f"# schema_version {spec['schema_version']}")
print()
print("TB_PARITY_ROWS=(")
for row in spec["rows"]:
    e = row["expect"]
    fields = [
        row["label"],
        row["nodes"],
        row["carried"],
        row.get("carried_provenance", ""),
        row.get("override", ""),
        e["size"],
        e["provenance"],
        "1" if e["undersized"] else "0",
        "1" if e["unschedulable"] else "0",
    ]
    for f in fields:
        if "|" in f:
            raise SystemExit(f"field contains the delimiter: {f!r}")
    print('  "' + "|".join(fields) + '"')
print(")")
PY
}

if (( CHECK )); then
  if ! diff -u "$OUT" <(_emit) >/dev/null 2>&1; then
    echo "PARITY TABLE DRIFT: $OUT does not match $SRC" >&2
    diff -u "$OUT" <(_emit) | head -30 >&2 || true
    echo "" >&2
    echo "Run scripts/gen-installer-parity.sh to regenerate it." >&2
    exit 1
  fi
  echo "parity table matches $SRC"
else
  _emit > "$OUT"
  echo "regenerated $OUT ($(grep -c '^  "' "$OUT") rows)"
fi
