#!/usr/bin/env bash
#
# gen-installer-parity.sh — flatten scripts/tests/fixtures/installer_parity.json
# into a sourceable bash table (client#772).
#
# bats has no guaranteed JSON parser (jq is not a prerequisite — see the
# helm-namespace note in lib/install-client-helm.sh), so the shared fixture is
# flattened for the bash side exactly the way envelope_vectors.bash already is.
# The Pester side reads the JSON directly; PowerShell has ConvertFrom-Json.
#
# One fixture, two readers. If they ever disagree, one has drifted — which is
# the whole point of the file.
#
# Usage:
#   scripts/gen-installer-parity.sh           # regenerate the bash table
#   scripts/gen-installer-parity.sh --check   # verify, change nothing (CI)

set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."

SRC="scripts/tests/fixtures/installer_parity.json"
OUT="scripts/tests/fixtures/installer_parity.bash"

CHECK=0
[[ "${1:-}" == "--check" ]] && CHECK=1

[[ -f "$SRC" ]] || { echo "[ERROR] $SRC is missing" >&2; exit 1; }
command -v python3 >/dev/null 2>&1 || {
  echo "[ERROR] python3 is required to regenerate the parity table" >&2
  exit 1
}

_emit() {
  python3 - "$SRC" <<'PY'
import json, sys

with open(sys.argv[1]) as fh:
    spec = json.load(fh)

print("# GENERATED by scripts/gen-installer-parity.sh — do not hand-edit.")
print("# Source of truth: scripts/tests/fixtures/installer_parity.json (client#772)")
print("#")
print("# One row per cluster state. Fields, pipe-separated:")
print("#   label|nodes|carried|carried_provenance|override|size|provenance|undersized|unschedulable|limits")
print("#")
print("# `nodes` is semicolon-separated node lines, as kubectl's jsonpath emits them:")
print("# '<cpu> <memory>' plus an optional third field, '<spec.unschedulable>'.")
print("# Unschedulable is omitempty, so a schedulable node emits nothing there and")
print("# both readers see a two-field line -- which is why the pre-backend#2237 rows")
print("# below still carry two fields. Only a CORDONED node emits the literal 'true'.")
print("# `carried` is 'none', 'read-fails', 'read-empty',")
print("# or the RESOURCE_LIMITS value a previous release carries.")
print("# `limits` is what RESOURCE_LIMITS gets: `size` minus its cpu dimension")
print("# (backend#2418 L0.2). NOT the same string as `size` any more.")
print(f"# schema_version {spec['schema_version']}")
print()
print("TB_PARITY_ROWS=(")
for row in spec["rows"]:
    e = row["expect"]
    fields = [
        row["label"],
        row["nodes"],
        row["carried"],
        row.get("carried_provenance", ""),
        row.get("override", ""),
        e["size"],
        e["provenance"],
        "1" if e["undersized"] else "0",
        "1" if e["unschedulable"] else "0",
        # schema_version 2 (backend#2418): the LIMITS half, which is no longer
        # the same string as `size`. A second shared contract between the twins,
        # and one a real divergence was already found in -- see verdict_fields.
        e["limits"],
    ]
    for f in fields:
        if "|" in f:
            raise SystemExit(f"field contains the delimiter: {f!r}")
    print('  "' + "|".join(fields) + '"')
print(")")

# backend#2460: the kubelet drop-in's reservation BEHAVIOUR both writers must
# show (the values are generated into the twins and held equal by the agreement
# guard; this is the shape, driven through each real writer).
kr = spec.get("kubelet_reservation")
if not kr:
    raise SystemExit("installer_parity.json has no kubelet_reservation section")


def arr(name, items):
    for it in items:
        if '"' in it:
            raise SystemExit(f"{name}: item contains a double quote: {it!r}")
    print(f"{name}=(")
    for it in items:
        print(f'  "{it}"')
    print(")")


print()
print("# kubelet drop-in reservation shape (backend#2460); see the JSON's kubelet_reservation.purpose")
print(f'TB_PARITY_RESERVATION_PLATFORMS_VAR="{kr["measured_platforms_variable"]}"')
print(f'TB_PARITY_RESERVATION_UNMEASURED_PROBE="{kr["unmeasured_probe_platform"]}"')
arr("TB_PARITY_RESERVATION_EMITTED_MEASURED", kr["emitted_for_a_measured_platform"])
arr("TB_PARITY_RESERVATION_NEVER_UNMEASURED", kr["never_emitted_for_an_unmeasured_platform"])
arr("TB_PARITY_RESERVATION_NEVER_RESTATED", kr["never_restated_from_k3s"])
arr("TB_PARITY_RESERVATION_ALWAYS", kr["always_emitted"])
PY
}

if (( CHECK )); then
  if ! diff -u "$OUT" <(_emit) >/dev/null 2>&1; then
    echo "PARITY TABLE DRIFT: $OUT does not match $SRC" >&2
    diff -u "$OUT" <(_emit) | head -30 >&2 || true
    echo "" >&2
    echo "Run scripts/gen-installer-parity.sh to regenerate it." >&2
    exit 1
  fi
  echo "parity table matches $SRC"
else
  _emit > "$OUT"
  echo "regenerated $OUT ($(grep -c '^  "' "$OUT") rows)"
fi
