apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.mysqlPvc.name }}
spec:
  storageClassName: {{ .Values.storageClass.name }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.mysqlPvc.storage }}