apiVersion: v1
kind: Secret
metadata:
  name: tracebloc-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  EDGE_PASSWORD: {{ .Values.secrets.edgePassword | b64enc | quote }}
  CONNECTION_STRING: {{ .Values.secrets.connectionString | b64enc | quote }}
  AZURE_STORAGE_CONNECTION_STRING: {{ .Values.secrets.azureStorageConnectionString | b64enc | quote }} 