#!/usr/bin/env bash
# =============================================================================
#  migrate-tenant.sh — parameterized chart-family migration runbook
#  generalising the protocol validated on stg (2026-04-27) and hasan-prod
#  (2026-04-27). Reads tenant config + secrets from tenant-config.env (same
#  file generate.sh consumes).
#
#  USAGE
#    ./migrate-tenant.sh phase1 <tenant>
#    ./migrate-tenant.sh phase2 <tenant>
#
#  Step through it. Don't pipe both phases together — Phase 1 produces
#  artifacts and an AWS Backup recovery point; you eyeball the artifacts
#  and confirm "go" before Phase 2 (the destructive part).
#
#  Phase 1 is idempotent and re-runnable.
#  Phase 2 is one-shot per tenant and assumes Phase 1 ran cleanly.
#
#  Required env / config
#    TENANT_CONFIG  path to tenant-config.env (default: ./tenant-config.env)
#    CTX            kubectl/helm --context (default: the prod EKS context)
#    CHART_PATH     local chart dir (default: ./client, run from repo root)
#    MYSQL_ROOT_PW  mysqldump root password (default: image-baked legacy pw)
# =============================================================================
set -euo pipefail

CONFIG="${TENANT_CONFIG:-$(dirname "$0")/tenant-config.env}"
CTX="${CTX:-arn:aws:eks:eu-central-1:872515254613:cluster/tracebloc-clients-prod}"
CHART_PATH="${CHART_PATH:-./client}"
BACKUP_VAULT="${BACKUP_VAULT:-aws/efs/automatic-backup-vault}"
BACKUP_ROLE="${BACKUP_ROLE:-arn:aws:iam::872515254613:role/TraceblocBackupOnDemandRole}"

[[ -f "$CONFIG" ]] || { echo "missing $CONFIG — copy tenant-config.example.env, fill it in" >&2; exit 2; }
# shellcheck disable=SC1090
source "$CONFIG"

# EFS_FS comes from the sourced config. Allow EFS_FS_OVERRIDE as a
# post-source env knob so operators can target a non-default filesystem
# without editing the config — pre-source assignment was a no-op because
# `source` unconditionally re-sets EFS_FS from the config file.
[[ -n "${EFS_FS_OVERRIDE:-}" ]] && EFS_FS="$EFS_FS_OVERRIDE"
[[ -n "${EFS_FS:-}" ]] || { echo "EFS_FS must be set in $CONFIG or via EFS_FS_OVERRIDE env" >&2; exit 2; }

# MYSQL_ROOT_PW must come from the env or tenant-config.env. It's the
# legacy image-baked root password that mysqldump needs. Refuse to run
# without it rather than hardcode a default — keeps secrets out of git.
# Also reject the literal __PLACEHOLDER__ shipped in the example so an
# unfilled config fails fast here instead of mid-Phase-1 with an opaque
# "Access denied" from mysqldump inside kubectl exec.
[[ -n "${MYSQL_ROOT_PW:-}" ]] || { echo "MYSQL_ROOT_PW must be set in $CONFIG or env" >&2; exit 2; }
case "$MYSQL_ROOT_PW" in
  *__*__*) echo "MYSQL_ROOT_PW still contains placeholder __...__ — set the real legacy mysql root password in $CONFIG" >&2; exit 2 ;;
esac

# Pluck the requested tenant's row out of TENANTS
ACTION="${1:-}"; TARGET="${2:-}"
[[ "$ACTION" =~ ^(phase1|phase2)$ && -n "$TARGET" ]] || {
  echo "usage: $0 phase1|phase2 <tenant>" >&2; exit 2; }

ROW=""
while IFS= read -r LINE; do
  LINE="${LINE# }"; LINE="${LINE% }"
  [[ -z "$LINE" || "$LINE" == \#* ]] && continue
  IFS='|' read -r T _ _ _ _ _ _ _ _ <<<"$LINE"
  T="$(echo "$T" | xargs)"
  [[ "$T" == "$TARGET" ]] && { ROW="$LINE"; break; }
done <<<"$TENANTS"
[[ -n "$ROW" ]] || { echo "tenant '$TARGET' not found in $CONFIG" >&2; exit 2; }

IFS='|' read -r TENANT RELEASE NS CLIENT_ID CLIENT_PASSWORD SC_NAME PV_MYSQL PV_LOGS PV_DATA <<<"$ROW"
TENANT="$(echo "$TENANT" | xargs)"
RELEASE="$(echo "$RELEASE" | xargs)"
NS="$(echo "$NS" | xargs)"
SC_NAME="$(echo "$SC_NAME" | xargs)"
PV_MYSQL="$(echo "$PV_MYSQL" | xargs)"
PV_LOGS="$(echo "$PV_LOGS" | xargs)"
PV_DATA="$(echo "$PV_DATA" | xargs)"

WORKDIR=/tmp/tracebloc-migration-$TENANT
ARTIFACTS_OK=("$WORKDIR/values.yaml" "$WORKDIR/storageclass.yaml" "$WORKDIR/pvcs.yaml")

kctx() { kubectl --context "$CTX" "$@"; }
hctx() { helm --kube-context "$CTX" "$@"; }
banner() { printf "\n=== %s ===\n" "$*"; }

# Portable helpers — operators run this from macOS or Linux. The md5 line in
# parts.md5 is generated by md5sum inside the pod, so format-compatibility is
# what matters: md5sum on Linux and md5 -q on macOS both yield the bare hex
# digest. wc -c sidesteps stat's BSD vs GNU flag split.
if command -v md5sum >/dev/null 2>&1; then
  _md5() { md5sum "$1" | awk '{print $1}'; }
elif command -v md5 >/dev/null 2>&1; then
  _md5() { md5 -q "$1"; }
else
  echo "neither md5sum nor md5 found in PATH" >&2; exit 2
fi
_size() { wc -c < "$1" | tr -d '[:space:]'; }

phase1() {
  banner "Phase 1.1 — confirm pre-flight state"
  for f in "${ARTIFACTS_OK[@]}"; do
    [[ -f "$f" ]] || { echo "MISSING: $f — run ./generate.sh first" >&2; exit 1; }
  done

  banner "release in $NS"
  hctx list -n "$NS"

  banner "active workloads in namespace (jobs + non-tracebloc pods)"
  kctx get jobs -n "$NS" 2>&1 | tail -n +2
  kctx get pods -n "$NS" 2>&1 | tail -n +2 | grep -v -E "mysql|jobs-manager|manager|resource-monitor" | head -20 || true
  echo "If active training Jobs are listed: decide whether to wait or 'kubectl delete jobs -n $NS --all' (loses in-flight customer work)."

  banner "PVCs + PV reclaim policies"
  kctx get pvc -n "$NS" -o custom-columns="PVC:.metadata.name,SIZE:.spec.resources.requests.storage,PV:.spec.volumeName,STATUS:.status.phase"
  kctx get pv "$PV_MYSQL" "$PV_LOGS" "$PV_DATA" -o custom-columns="PV:.metadata.name,RECLAIM:.spec.persistentVolumeReclaimPolicy,STATUS:.status.phase,ACCESS:.spec.accessModes"

  banner "stored manifest keep-annotation status (expect: none — Option C path)"
  hctx get manifest "$RELEASE" -n "$NS" 2>/dev/null | grep -B2 -A1 'resource-policy' || echo "(none — confirms Option C is the right path)"

  banner "Phase 1.2 — mysqldump inside pod"
  POD=$(kctx -n "$NS" get pod -l 'app in (mysql-client)' -o jsonpath='{.items[0].metadata.name}' 2>/dev/null || true)
  [[ -z "$POD" ]] && POD=$(kctx -n "$NS" get pod -l "app=$RELEASE-mysql" -o jsonpath='{.items[0].metadata.name}' 2>/dev/null || true)
  [[ -z "$POD" ]] && POD=$(kctx -n "$NS" get pod -l "app=$TENANT-mysql" -o jsonpath='{.items[0].metadata.name}' 2>/dev/null || true)
  [[ -z "$POD" ]] && { echo "could not locate mysql pod by label; inspect: kctx -n $NS get pods" >&2; exit 1; }
  echo "mysql pod: $POD"

  echo "running mysqldump..."
  kctx -n "$NS" exec "$POD" -- bash -c "rm -f /tmp/${TENANT}-backup.sql.gz /tmp/${TENANT}-backup.sql.gz.part-* /tmp/parts.md5 && mysqldump -uroot -p'${MYSQL_ROOT_PW}' --single-transaction --routines --triggers --quick --hex-blob training_test_datasets | gzip > /tmp/${TENANT}-backup.sql.gz && ls -lh /tmp/${TENANT}-backup.sql.gz"

  echo "splitting + md5..."
  kctx -n "$NS" exec "$POD" -- bash -c "cd /tmp && split -b 5M -d -a 3 ${TENANT}-backup.sql.gz ${TENANT}-backup.sql.gz.part- && md5sum ${TENANT}-backup.sql.gz.part-* > /tmp/parts.md5 && wc -l /tmp/parts.md5"

  rm -f "$WORKDIR/parts.md5" "$WORKDIR/${TENANT}-backup.sql.gz"*
  kctx cp "${NS}/${POD}:/tmp/parts.md5" "$WORKDIR/parts.md5"

  echo "chunked cp (per-chunk md5 retry up to 4 attempts; transient failures self-heal)..."
  cd "$WORKDIR"
  total=$(wc -l < parts.md5 | tr -d ' ')
  done_count=0
  while IFS=' ' read -r expected part; do
    expected=$(echo "$expected" | tr -d '[:space:]')
    attempt=0; ok=false
    while [ "$attempt" -lt 4 ]; do
      attempt=$((attempt+1)); rm -f "$part"
      if kctx cp "${NS}/${POD}:/tmp/${part}" "./${part}" >/dev/null 2>&1; then
        actual=$(_md5 "./${part}" 2>/dev/null)
        if [ "$actual" = "$expected" ]; then ok=true; break; fi
      fi
      sleep 2
    done
    $ok || { echo "ABORT $part" >&2; exit 1; }
    done_count=$((done_count+1))
    [ $((done_count % 10)) -eq 0 ] && echo "  ${done_count}/${total} chunks"
  done < parts.md5
  cat ${TENANT}-backup.sql.gz.part-* > ${TENANT}-backup.sql.gz
  gzip -t ${TENANT}-backup.sql.gz && echo "DUMP OK — $(_size ${TENANT}-backup.sql.gz) bytes"
  cd - >/dev/null

  banner "Phase 1.3 — AWS Backup on-demand recovery point"
  JOB=$(aws backup start-backup-job \
    --backup-vault-name "$BACKUP_VAULT" \
    --resource-arn "arn:aws:elasticfilesystem:eu-central-1:872515254613:file-system/$EFS_FS" \
    --iam-role-arn "$BACKUP_ROLE" \
    --recovery-point-tags "{\"Purpose\":\"$TENANT-migration-$(date -u +%Y-%m-%d)\",\"Operator\":\"$(aws sts get-caller-identity --query Arn --output text)\",\"ChartFrom\":\"eks-1.0.x\",\"ChartTo\":\"client-1.x\",\"Release\":\"$RELEASE\"}" \
    --region eu-central-1 --query 'BackupJobId' --output text)
  echo "$JOB" > "$WORKDIR/backup-job-id"
  echo "BackupJobId=$JOB. Monitor:"
  echo "  aws backup describe-backup-job --backup-job-id $JOB --region eu-central-1 --query '[State,PercentDone]' --output text"

  banner "Phase 1.4 — render new chart against live cluster"
  hctx template "$RELEASE" "$CHART_PATH" -n "$NS" -f "$WORKDIR/values.yaml" --dry-run=server > "$WORKDIR/rendered.yaml" 2>&1 \
    || { echo "render failed — see $WORKDIR/rendered.yaml" >&2; exit 1; }
  echo "rendered to $WORKDIR/rendered.yaml ($(wc -l < "$WORKDIR/rendered.yaml") lines)"

  banner "Phase 1 done. Eyeball:"
  echo "  - $WORKDIR/${TENANT}-backup.sql.gz looks right (size > 0, gzip -t passes)"
  echo "  - AWS Backup job $JOB reaches COMPLETED before Phase 2"
  echo "  - $WORKDIR/values.yaml + pvcs.yaml + storageclass.yaml + rendered.yaml are sane"
  echo
  echo "When ready: $0 phase2 $TARGET"
}

phase2() {
  banner "Phase 2.0 — strip Helm ownership from StorageClass"
  echo "(Note: this is a NO-OP for uninstall behaviour, but cleans the live label state."
  echo " Documented in MIGRATIONS.md as ineffective — included here for symmetry only.)"

  banner "Phase 2.1 — helm uninstall (PVCs deleted, PVs go Released, SC deleted)"
  hctx uninstall "$RELEASE" -n "$NS"

  banner "Phase 2.2 — clear claimRef on the 3 PVs"
  for PV in "$PV_LOGS" "$PV_DATA" "$PV_MYSQL"; do
    kctx patch pv "$PV" --type=json -p='[{"op":"remove","path":"/spec/claimRef"}]'
  done
  kctx get pv "$PV_LOGS" "$PV_DATA" "$PV_MYSQL" -o custom-columns="PV:.metadata.name,STATUS:.status.phase,CLAIM:.spec.claimRef.name"

  banner "Phase 2.3 — re-create StorageClass, then pre-create PVCs"
  kctx apply -f "$WORKDIR/storageclass.yaml"
  kctx apply -f "$WORKDIR/pvcs.yaml"
  for PVC in client-logs-pvc client-pvc mysql-pvc; do
    kctx wait --for=jsonpath='{.status.phase}'=Bound pvc/"$PVC" -n "$NS" --timeout=60s
  done
  kctx get pvc -n "$NS" -o custom-columns="PVC:.metadata.name,STATUS:.status.phase,VOLUME:.spec.volumeName"

  banner "Phase 2.4 — helm install client-1.x"
  hctx install "$RELEASE" "$CHART_PATH" -n "$NS" -f "$WORKDIR/values.yaml"

  banner "Phase 2.5 — wait for pods Ready, then verify"
  # Bounded wait: Phase 2 just ran a destructive uninstall, so a freshly
  # installed release that fails to converge (image pull error, mysql kill-loop
  # recurrence, scheduler can't satisfy priorityClass, PVC binding fails) must
  # surface fast — an indefinite hang here delays operator action when the
  # tenant is at its most fragile. Override via READY_TIMEOUT (seconds).
  READY_TIMEOUT="${READY_TIMEOUT:-600}"
  deadline=$(( $(date +%s) + READY_TIMEOUT ))
  cur=""
  while :; do
    cur=$(kctx -n "$NS" get pod -l 'app in (mysql-client,manager)' --no-headers 2>/dev/null)
    # cur is empty in the routine post-install window before pods exist.
    # Guard explicitly: `grep -c .` exits 1 on no matches, which under
    # `set -euo pipefail` would terminate the script on the first iteration
    # instead of looping until the deadline. `echo "" | wc -l` returns 1
    # (echo adds a trailing newline), so we can't lean on wc alone either.
    if [[ -z "$cur" ]]; then
      total=0; ready=0
    else
      ready=$(echo "$cur" | awk '$2 ~ /^[0-9]+\/[0-9]+$/ && $3 == "Running" {split($2,a,"/"); if (a[1]==a[2]) print "ok"}' | wc -l | tr -d ' ')
      total=$(echo "$cur" | wc -l | tr -d ' ')
    fi
    [[ $total -ge 2 && $ready -eq $total ]] && break
    if [[ $(date +%s) -ge $deadline ]]; then
      echo "TIMEOUT — pods not Ready after ${READY_TIMEOUT}s. Current state:" >&2
      echo "$cur" >&2
      echo "Investigate: kctx -n $NS describe pod -l 'app in (mysql-client,manager)'" >&2
      exit 1
    fi
    sleep 5
  done
  echo "$cur"

  banner "keep annotation now in stored manifest? (expected: 3 PVC blocks)"
  hctx get manifest "$RELEASE" -n "$NS" | grep -B2 -A1 'resource-policy' | head -25

  banner "mysql data — top tables"
  MYSQL_POD=$(kctx -n "$NS" get pod -l app=mysql-client -o jsonpath='{.items[0].metadata.name}')
  kctx -n "$NS" exec "$MYSQL_POD" -- mysql -uroot -p"${MYSQL_ROOT_PW}" \
    -e "USE training_test_datasets; SELECT TABLE_NAME, TABLE_ROWS FROM information_schema.tables WHERE TABLE_SCHEMA='training_test_datasets' ORDER BY TABLE_ROWS DESC LIMIT 5;" 2>&1 | grep -v -E "Warning|Defaulted"

  banner "mysql v1.1.0 spec sanity"
  kctx -n "$NS" get pod -l app=mysql-client -o jsonpath='QoS={.items[0].status.qosClass} priorityClassName={.items[0].spec.priorityClassName} memReq={.items[0].spec.containers[0].resources.requests.memory} memLim={.items[0].spec.containers[0].resources.limits.memory} cpuLim="{.items[0].spec.containers[0].resources.limits.cpu}" liveTimeout={.items[0].spec.containers[0].livenessProbe.timeoutSeconds} restarts={.items[0].status.containerStatuses[0].restartCount}{"\n"}'
  echo
  echo "DONE — soak for 24h, then watch for kill-loop recurrence:"
  echo "  kubectl --context \$CTX describe pod mysql-client -n $NS | grep -A2 'Last State'"
}

case "$ACTION" in
  phase1) phase1 ;;
  phase2) phase2 ;;
esac
