{{- if .Values.storageClass.create }}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ .Values.storageClass.name }}
  namespace: {{ .Release.Namespace }}
provisioner: {{ .Values.storageClass.provisioner }}
allowVolumeExpansion: {{ .Values.storageClass.allowVolumeExpansion }}
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=999
  - gid=999
  - mfsymlinks
  - cache=strict
  - actimeo=30
parameters:
  skuName: {{ .Values.storageClass.parameters.skuName }}
{{- end }}